# Data Preprocessing

In [11]:
import pandas as pd

df = pd.read_csv("Resume.csv")

print(df.columns)
df.head()

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [12]:
# --- Dropping columns "ID" & "Resume_html" ---
df.drop(columns=["ID", "Resume_html"], inplace=True)
df.head()

                                          Resume_str Category
0           HR ADMINISTRATOR/MARKETING ASSOCIATE\...       HR
1           HR SPECIALIST, US HR OPERATIONS      ...       HR
2           HR DIRECTOR       Summary      Over 2...       HR
3           HR SPECIALIST       Summary    Dedica...       HR
4           HR MANAGER         Skill Highlights  ...       HR

# Text Preprocessing

In [15]:
import nltk

nltk.download("stopwords")
nltk.download("wordnet")
# nltk.download("punkt_tab") # For colab
nltk.download("punkt") # For local runtime

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>

False

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

stop_words = set(stopwords.words("english"))
lemmen = WordNetLemmatizer()

def text_preprocessing(text: str) -> str:
  text = text.lower()                                                # Lower case the text
  text = re.sub(r"[^\w\s]", " ", text)                               # Remove punctuation
  text = word_tokenize(text)                                         # Tokenize
  text = [word for word in text if word not in stop_words]           # Remove stop words
  text = [word for word in text if word.isalpha() and len(word) > 2] # Remove numbers and short words
  text = [lemmen.lemmatize(word) for word in text]                   # Lemmentize word (running -> run)
  return " ".join(text)


df["Resume_str"] = df["Resume_str"].apply(text_preprocessing)
df.head()